# Generated by Django 2.2.12 on 2020-07-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
