# Generated by Django 2.2.12 on 2020-07-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200707_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='parent_message',
            field=models.IntegerField(default=0, verbose_name='回复的留言ID'),
        ),
    ]
